export const GET_USER = "GET_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const CHANGE_EMAIL_INPUT = "CHANGE_EMAIL_INPUT"
export const CHANGE_PASSWORD_INPUT = "CHANGE_PASSWORD_INPUT"
export const CHANGE_NAME_INPUT = "CHANGE_NAME_INPUT"
export const CHANGE_USERNAME_INPUT = "CHANGE_USERNAME_INPUT"

//Nico's additions
